### ISSUE TITLE
Autostart registers app under Update.exe in Windows

### ISSUE THREAD

**Issue by agustinmista** [agustinmista/positron#12]
Autostart itself looks good, app got registerd and did start automatically.
The only thing I've found is that the app is registered with the "update.exe" and not with "positron.exe".
Is that intentional?

![image](https://user-images.githubusercontent.com/47973549/230138637-5d24edb2-a764-4c15-9cf0-ecef7ac3a14e.png)

![image](https://user-images.githubusercontent.com/47973549/230138932-81d11c90-5c1f-4672-9f5c-810f1df75dab.png)

_Originally posted by @martinhoess in https://github.com/agustinmista/positron/issues/11#issuecomment-1497756870_

**Comment by martinhoess** [comment]
I can live with that. 
There is also an (old) discussion here that does not offer a real solution either: https://github.com/Squirrel/Squirrel.Windows/issues/400

Other (Electron) apps seem to have split this up somehow. At least I have a separate updater folders for Ferdi and Bitwarden (but I have no idea when this is executed and if these projects also use Squirrel).

**Comment by agustinmista** [comment]
Alright, let's close this issue until someone else complains about it then :)
