### ISSUE TITLE
Can't use F13-F24 on Fedora 38

### ISSUE THREAD

**Issue by pacjo** [agustinmista/positron#15]
Basically the title. F1-F12 work fine. F13-F24 with `ctrl` and `shift` work too, but they don't work with `ctrl` or `shift` alone.

**Comment by agustinmista** [comment]
Interesting. I tried those accelerators both in Windows and Ubuntu and they seem to be working. In your case, I think we need to establish whether:

1. The accelerator is already taken by another process
    When this happens, the OS will usually let you bind it again without complaining, but then it just doesn't work. See this note from the [Electron documentation](https://www.electronjs.org/docs/latest/api/global-shortcut):
    "When the accelerator is already taken by other applications, this call will silently fail. This behavior is intended by operating systems, since they don't want applications to fight for global shortcuts."

2. The accelerator is already taken by the Electron runtime
   This is likely what's going on with #13, but I really don't think that's the problem here.

3. There's something fishy with the Electron's `globalShortcut` API on Fedora

Some questions:

* Does the app accepts those accelerators or do you get an error message like in #13 instead?

* Could you please also share the strings you're using for the accelerators so I can test them here?

* Could you please paste here the console output from the app after you try to bind and use those accelerators?

**Comment by pacjo** [comment]
> Does the app accepts those accelerators or do you get an error message like in https://github.com/agustinmista/positron/issues/13 instead?

I get the exactly same error as in #13.
After some more digging it looks like those keys are mapped by system to various functions (simmilar purpose to the function row on laptops. Keys F1-F12 work fine and keys F13-f24 behave as if `fn` was pressed. F13 for example opens settings and F20 mutes/unmutes mic, others show up as `LaunchApplication10(some number)`)

Here's the output of QMK keyboard tester (not the best tool but shows my point well):
```
KEY-UP   - QMK:         Event key: Unidentified Code: F13           KeyCode: 0 in NaNms
KEY-DOWN - QMK:         Event key: LaunchApplication6 Code: F14           KeyCode: 0
KEY-UP   - QMK:         Event key: LaunchApplication6 Code: F14           KeyCode: 0 in 61.000ms
KEY-DOWN - QMK:         Event key: LaunchApplication7 Code: F15           KeyCode: 0
KEY-UP   - QMK:         Event key: LaunchApplication7 Code: F15           KeyCode: 0 in 72.000ms
KEY-DOWN - QMK:         Event key: LaunchApplication8 Code: F16           KeyCode: 0
KEY-UP   - QMK:         Event key: LaunchApplication8 Code: F16           KeyCode: 0 in 75.000ms
KEY-DOWN - QMK:         Event key: LaunchApplication9 Code: F17           KeyCode: 0
KEY-UP   - QMK:         Event key: LaunchApplication9 Code: F17           KeyCode: 0 in 66.000ms
KEY-DOWN - QMK:         Event key: LaunchApplication10 Code: F18           KeyCode: 0
KEY-UP   - QMK:         Event key: LaunchApplication10 Code: F18           KeyCode: 0 in 64.000ms
KEY-DOWN - QMK:         Event key: Unidentified Code: F19           KeyCode: 0
KEY-UP   - QMK:         Event key: Unidentified Code: F19           KeyCode: 0 in 83.000ms
KEY-UP   - QMK:         Event key: Unidentified Code: F20           KeyCode: 0 in NaNms
KEY-UP   - QMK:         Event key: Unidentified Code: F21           KeyCode: 0 in NaNms
KEY-UP   - QMK:         Event key: Unidentified Code: F22           KeyCode: 0 in NaNms
KEY-UP   - QMK:         Event key: Unidentified Code: F22           KeyCode: 0 in NaNms
KEY-DOWN - QMK:         Event key: Unidentified Code: F24           KeyCode: 0
KEY-UP   - QMK:         Event key: Unidentified Code: F24           KeyCode: 0 in 61.000ms
```
`Code` is detected well, but `Event key` is being passed to apps. 

> Could you please also share the strings you're using for the accelerators so I can test them here?

I'm just putting in `F13` without any modifiers

> Could you please paste here the console output from the app after you try to bind and use those accelerators?

I think I can't. App doesn't even allow my to enable the shortcut.

**Comment by pacjo** [comment]
I'm just updating this, as I found a solution to make it work under Wayland. So:

I you run this command `cat /etc/default/keyboard` you should get the config that your keyboard is using. In my case:
```
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="pl"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
```
so I'll be searching for the config `pc105`

Open this file `/usr/share/X11/xkb/symbols/inet`, you will see some generic configurations at the start, then keyboard specific ones. I'm interested in the `pc105`, which looks like this:
```
xkb_symbols "pc105" {
    include "inet(media_nav_acpi_common)"
};
```
if you see FK* keys here, change them (there is "example" below). I don't have them, so I will look in the included `media_nav_acpi_common`, which looks like this:
```
xkb_symbols "media_nav_acpi_common" {
    include "inet(media_common)"
    include "inet(nav_common)"
    include "inet(acpi_common)"
};
```
...and no FK* keys here too. In such case we'll edit the general config. This one is at the top at starts with something like this:
```
// Evdev Standardized Keycodes
partial alphanumeric_keys
xkb_symbols "evdev" {
    key <MUTE>   {      [ XF86AudioMute         ]       };
    key <VOL->   {      [ XF86AudioLowerVolume  ]       };
    key <VOL+>   {      [ XF86AudioRaiseVolume  ]       };
    key <POWR>   {      [ XF86PowerOff          ]       };
    key <STOP>   {      [ Cancel                ]       }
                                  ...
```
Scroll down some more and you will find sections with keys FK*. I have this one:
```
    key <FK21>   {      [ XF86TouchpadToggle    ]       };
    key <FK22>   {      [ XF86TouchpadOn        ]       };
    key <FK23>   {      [ XF86TouchpadOff       ]       };

    key <FK20>   {      [ XF86AudioMicMute      ]       };
```
and this:
```
    key <FK13>   {      [ XF86Tools         ]       };
    key <FK14>   {      [ XF86Launch5       ]       };
    key <FK15>   {      [ XF86Launch6       ]       };
    key <FK16>   {      [ XF86Launch7       ]       };
    key <FK17>   {      [ XF86Launch8       ]       };
    key <FK18>   {      [ XF86Launch9       ]       };
```

change them to:
```
    key <FK21>   {      [ F21                   ]       };
    key <FK22>   {      [ F22                   ]       };
    key <FK23>   {      [ F23                   ]       };
    key <FK24>   {      [ F24                   ]       };
    key <FK20>   {      [ F20                   ]       };
```
and
```
    key <FK13>   {      [ F13                    ]       };
    key <FK14>   {      [ F14                    ]       };
    key <FK15>   {      [ F15                    ]       };
    key <FK16>   {      [ F16                    ]       };
    key <FK17>   {      [ F17                    ]       };
    key <FK18>   {      [ F18                    ]       };
    key <FK19>   {      [ F19                    ]       };
```
I added keys F19 and F24 which weren't in original configurations. Save and reboot. Now F13 - F24 keys will return normal values instead of opening settings or other things.

**Comment by agustinmista** [comment]
This is a great piece of information for future users. Thanks a lot for taking the time to post it here 😄
